print("\n\t\t\t  404\n\n\n")
print("\n\n\t\t\t  Page")
print("\n\t\t\t  not")
print("\n\t\t\t  found\n\n\n")
print("\n\n\t\t\t  Sorry")
print("\n\t\t\t  about")
print("\n\t\t\t  that\n\n\n")
print("\n\n\n\t\t\t¯\_(ツ)_/¯")